// <auto-generated />
using System;
using CurrencyWatchlist.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CurrencyWatchlist.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CurrencyWatchlistDbContext))]
    [Migration("20260831103526_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("CurrencyWatchlist.Domain.Entities.AlertEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.ToTable("AlertEvents");
                });

            modelBuilder.Entity("CurrencyWatchlist.Domain.Entities.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("WatchlistItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WatchlistItemId", "IsActive");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("CurrencyWatchlist.Domain.Entities.RateSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SourceTimestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrency", "QuoteCurrency", "SourceTimestamp");

                    b.ToTable("RateSnapshots");
                });

            modelBuilder.Entity("CurrencyWatchlist.Domain.Entities.Watchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Watchlists");
                });

            modelBuilder.Entity("CurrencyWatchlist.Domain.Entities.WatchlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("WatchlistId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrency", "QuoteCurrency");

                    b.HasIndex("WatchlistId", "BaseCurrency", "QuoteCurrency")
                        .IsUnique();

                    b.ToTable("WatchlistItems");
                });

            modelBuilder.Entity("CurrencyWatchlist.Domain.Entities.AlertEvent", b =>
                {
                    b.HasOne("CurrencyWatchlist.Domain.Entities.AlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertRule");
                });

            modelBuilder.Entity("CurrencyWatchlist.Domain.Entities.AlertRule", b =>
                {
                    b.HasOne("CurrencyWatchlist.Domain.Entities.WatchlistItem", "WatchlistItem")
                        .WithMany("AlertRules")
                        .HasForeignKey("WatchlistItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WatchlistItem");
                });

            modelBuilder.Entity("CurrencyWatchlist.Domain.Entities.WatchlistItem", b =>
                {
                    b.HasOne("CurrencyWatchlist.Domain.Entities.Watchlist", "Watchlist")
                        .WithMany("Items")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("CurrencyWatchlist.Domain.Entities.Watchlist", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CurrencyWatchlist.Domain.Entities.WatchlistItem", b =>
                {
                    b.Navigation("AlertRules");
                });
#pragma warning restore 612, 618
        }
    }
}
