services:
  - type: web
    name: currency-watchlist-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /api/watchlists
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
      - key: Cors__AllowedOrigins__0
        value: http://localhost:3000
      - key: Cors__AllowedOrigins__1
        value: https://currency-watchlist.vercel.app
